name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Compile spawner
      shell: cmd
      run: cl /EHsc /std:c++20 main.cc spawn.cc

    - name: Run spawner
      shell: cmd
      run: main.exe
